### ISSUE TITLE
Swag decision ( tshirts, stickers,...)

### ISSUE THREAD

**Issue by jgrumboe** [cloud-native-austria/kcd-austria#118]

**Comment by erikauer** [comment]
Updates from @KatharinaSick:

T-Shirts: samples are currently produced and will be sent to my place. I'll send you pictures as soon as I have them

Print materials & assets: I have created a list of assets that we still need to create until the conference. It would be great if you could take a look at it in the sync today and ping me if there is anything missing.

Print materials & assets we need for the conference:

- Badges
- Rollups
- 1 big rollup to place somewhere for people to take pictures 
- 2 smaller rollups so that we can place one on each stage 
- Image/Video to show on the monitors in front of the cinema rooms (does somebody know the exact resolution of those monitors?)
- Image/Video to show on the reception monitor (does somebody know the exact resolution of this monitor?)
- T-Shirts
- Stickers
- Slide template for intro/outro slides
- Intro/Outro video for recordings
- Event Info page on website

**Comment by jgrumboe** [comment]
Tshirts for everyone who wants via registration form
stickers for sticker table
little speaker swag
